### PR TITLE
give access to flags in ParcelConverter

### PR DESCRIPTION
**Pull request by mboudraa**

### CODE REVIEW

**Comment by johncarl81** [comment]
Do you have a specific need to access the flags?

**Comment by mboudraa** [comment]
Actually, since it's provided by the android API, It makes me feel uncomfortable to force the flag to zero instead of passing the value given by the framework

**Comment by johncarl81** [comment]
I am aware of the flags `CONTENTS_FILE_DESCRIPTOR` and `PARCELABLE_WRITE_RETURN_VALUE`: https://developer.android.com/reference/android/os/Parcelable.html#writeToParcel(android.os.Parcel, int), where did you find the flag about serializing a CharSequence?

**Comment by johncarl81** [comment]
And, in fact, the `writeValue` method on the `Parcel` (the method we're able to shortcut using code generation) sets the flag to zero: https://github.com/android/platform_frameworks_base/blob/master/core/java/android/os/Parcel.java#L1405

**Comment by mboudraa** [comment]
I know you are aware of this flag. Sorry if i make you feel bad about this.
TextUtils.writeToParcel uses this flag internally.
https://developer.android.com/reference/android/text/TextUtils.html#writeToParcel(java.lang.CharSequence, android.os.Parcel, int)

**Comment by mboudraa** [comment]
Here is the piece of code using this.
`public static void writeToParcel(CharSequence cs, Parcel p, int parcelableFlags) {
        if (cs instanceof Spanned) {
            p.writeInt(0);
            p.writeString(cs.toString());

            Spanned sp = (Spanned) cs;
            Object[] os = sp.getSpans(0, cs.length(), Object.class);

            // note to people adding to this: check more specific types
            // before more generic types.  also notice that it uses
            // "if" instead of "else if" where there are interfaces
            // so one object can be several.

            for (int i = 0; i < os.length; i++) {
                Object o = os[i];
                Object prop = os[i];

                if (prop instanceof CharacterStyle) {
                    prop = ((CharacterStyle) prop).getUnderlying();
                }

                if (prop instanceof ParcelableSpan) {
                    final ParcelableSpan ps = (ParcelableSpan) prop;
                    final int spanTypeId = ps.getSpanTypeIdInternal();
                    if (spanTypeId < FIRST_SPAN || spanTypeId > LAST_SPAN) {
                        Log.e(TAG, "External class \"" + ps.getClass().getSimpleName()
                                + "\" is attempting to use the frameworks-only ParcelableSpan"
                                + " interface");
                    } else {
                        p.writeInt(spanTypeId);
                        ps.writeToParcelInternal(p, parcelableFlags);
                        writeWhere(p, sp, o);
                    }
                }
            }

            p.writeInt(0);
        } else {
            p.writeInt(1);
            if (cs != null) {
                p.writeString(cs.toString());
            } else {
                p.writeString(null);
            }
        }
    }`

**Comment by johncarl81** [comment]
I'm looking for the reason to accept this change... can you give me a clear reason why to connect these flags?

**Comment by johncarl81** [comment]
@mboudraa, could you provide a concrete reason to add the flag to the API?

**Comment by johncarl81** [comment]
Closing due to inactivity.

**Pull request closed without merging**
