### PR TITLE
use classloader to load class

### PR DESCRIPTION
**Pull request by huaf22**

### CODE REVIEW

**Comment by johncarl81** [comment]
Can you outline what problem this solves?

**Comment by huaf22** [comment]
when the model class and the parceler library is not in the same apk will appear classnotfound

**Comment by johncarl81** [comment]
Ah, you're right.

**Comment by johncarl81** [comment]
I've deployed this under 1.1.11-SNAPSHOT to maven central if you want to give it a try.

Thanks for your contribution!

**Comment by kaciula** [comment]
@johncarl81 I can't find the 1.1.11-SNAPSHOT anywhere. I am also getting ClassNotFoundException on a Huawei tablet

**Comment by johncarl81** [comment]
what class is not found @kaciula?

**Comment by kaciula** [comment]
The class that is not found at runtime is MyClass$$Parcelable. It is being generated but at runtime, it is not being found. Also I am using the proguard settings mentioned in the README. It's happening only with the release version and not the debug version. However, I am using the same proguard settings for both.

After doing some small unrelated code changes, I no longer get the exception.

**Pull request merged**
