### PR TITLE
Update README.asciidoc

### PR DESCRIPTION
**Pull request by Naitbit**
Added: missing parenthesis to example

### CODE REVIEW

**Comment by johncarl81** [comment]
Nice catch.  Would you like to update the website as well https://github.com/johncarl81/parceler-site

**Comment by Naitbit** [comment]
I may be looking in the wrong place, but http://parceler.org/ already looks correct.

**Comment by johncarl81** [comment]
I went ahead and updated it myself.. sorry, should have let you know.

**Comment by Naitbit** [comment]
No problem

**Pull request merged**
