### PR TITLE
Added configuration for proguard #77

### PR DESCRIPTION
**Pull request by emartynov**
I've added rules for ```proguard``` that I copied from your example app. It works for my project. Please review and accept pull request

### CODE REVIEW

**Comment by emartynov** [comment]
John, sorry for delay in answer. I'm trying to minimise proguard directives. My project proguard file is huge and I afraid that some parts might influence each other. So I've tried to test the new set of progurad rules with example app. Unfortunately my `mvn android:deploy` is failing. I'm checking what is the issue and what will be the fastest way to check obfuscation

**Comment by emartynov** [comment]
Hi John,

sorry for delay in progress. I've created test simplest project to determine correct and simplest proguard configuration:
https://github.com/emartynov/TestProguardParceler

It is only one Data class with one field. What other variants of Parcel library should I add to check that proguard doesn't break anything.

**Comment by johncarl81** [comment]
Awesome @emartynov!

I'll check out your example in depth and let you know what could be added.

What do you think about adding this example to the examples folder in parceler?  I'd welcome a PR.

Can you rebase this commit?

**Comment by emartynov** [comment]
I've tried to re-base but looks like I made some noise with merge commit. Let me know if it is acceptable

**Comment by johncarl81** [comment]
Reviewing #98, we may want to add this rule as well (or something like it):
```
keep class org.parceler.NonParcelRepository
```

If you rebase again and handle the merge conflict then (`git rebase master proguard-documentation`)

**Comment by emartynov** [comment]
John, is there example of data that can cause this issue?

**Comment by johncarl81** [comment]
`ListParcelableFactory` and `ListParcelable` used to serialize `List<ExampleParcel>`:
https://github.com/johncarl81/parceler/blob/master/parceler-api/src/main/java/org/parceler/NonParcelRepository.java#L76
and
https://github.com/johncarl81/parceler/blob/master/parceler-api/src/main/java/org/parceler/NonParcelRepository.java#L269

**Comment by emartynov** [comment]
So basically if I have try to wrap `List` of `@Parcel` class instances it should be involved. Correct?

I've already included it to my example and with original two lines of proguard configuration it still works. Can you take a look?

**Comment by johncarl81** [comment]
Oh nice... it must be included because of the `-keep class org.parceler.Parceler$$Parcels` rule.

Can you do another rebase so we have one clean commit to the `README.asciidoc` and I'll merge?

**Comment by emartynov** [comment]
I'm going to delete pull request and just create new one. I just want things and don't have much experience with history modification

**Pull request closed without merging**
